name: Install and Run httpd with ngrok

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install httpd
      run: |
        sudo apt-get update
        sudo apt-get install -y apache2
        
    - name: Download WAR file
      run: |
        wget https://raw.githubusercontent.com/MUSTAFA-A-KHAN/freeevps2/main/WebAppJava-0.0.1-SNAPSHOT.war -O your-app.war

    - name: Start httpd
      run: sudo service apache2 start

    - name: Copy WAR file to Tomcat webapps directory
      run: |
        sudo cp your-app.war /var/lib/tomcat9/webapps/

    - name: Restart Tomcat
      run: |
        sudo systemctl restart tomcat9
    
    - name: Display Apache version
      run: apachectl -v

    - name: Display Apache status
      run: sudo service apache2 status

    - name: Download and extract ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip

    - name: Start ngrok and expose Apache port
      run: |
        ./ngrok authtoken 1x4H0neaMfnRX0ATJsuLhMP3lt3_tEj68PPQBGSMmY8wZMHH
        ./ngrok http 80

    # Add additional steps as needed for your specific use case
