name: Apache Ngrok Workflow

on: [push]

jobs:
  test_and_tunnel:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Apache
      run: |
        $installDir = "C:\tools"
        Install-ChocoPackage apache-httpd -ArgumentList "--force", "--params", "/installLocation:$installDir /port:8080" # Change port to 8080 or another available port
        Start-Service -Name Apache
        Start-Sleep -Seconds 10 # Wait for Apache to start (adjust as needed)

    - name: Test Apache
      run: |
        # Add your Apache test commands here
        # For example:
        $apacheStatus = Get-Service -Name Apache | Select-Object -ExpandProperty Status
        if ($apacheStatus -eq 'Running') {
          Write-Host "Apache is running successfully."
        } else {
          Write-Host "Apache is not running. Please check the installation."
          exit 1
        }

    - name: Start ngrok and expose Apache port
      run: |
        Invoke-WebRequest 'https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip' -OutFile 'ngrok-stable-windows-amd64.zip'
        Expand-Archive -Path '.\ngrok-stable-windows-amd64.zip' -DestinationPath '.\'
        java -version
        .\ngrok authtoken 1x4H0neaMfnRX0ATJsuLhMP3lt3_tEj68PPQBGSMmY8wZMHH
        .\ngrok.exe http 8080 # Use the port configured for Apache

