name: Install Tomcat and Check Status

on: [push]

jobs:
  install-tomcat:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Wait for Tomcat to start and serve requests
      run: |
        $url = "http://localhost:8080/"
        $maxAttempts = 10
        $attempts = 0
        $installDir = "C:\tools"
        # Install latest apache in chocolatey
        
        Install-ChocoPackage apache-httpd -ArgumentList "--force", "--params", "/installLocation:$installDir /port:80"
         # Stop and disable Apache service
        Stop-Service -Name Apache
        Set-Service -Name Apache -StartupType Disabled
         # Start w3svc service
        Start-Service -Name w3svc

        # Invoke Pester Tests
        Invoke-PesterTests -TestFile "Apache"

         
        while ($true) {
          try {
            # Start Tomcat
            Start-Process -FilePath "D:\a\Tomcatrepo\Tomcatrepo\Tomcat\apache-tomcat-10.0.14\bin\startup.bat" -NoNewWindow -Wait
            Write-Host "Tomcat has started successfully."
            curl "http://localhost:8080"

            # Check if Tomcat is serving requests
            $response = Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 5
            echo $response.StatusCode
            if ($response.StatusCode -eq 200) {
                Write-Host "Tomcat has started successfully and is serving requests."
                break
            } else {
                Write-Host "$response"
                Write-Host " $response.StatusCode"
                Write-Host "Waiting for Tomcat to start and serve requests. Attempt $($attempts + 1) of $maxAttempts..."
                Start-Sleep -Seconds 10
                $attempts++
            }
          } catch {
            Write-Host "Waiting for Tomcat to start. Attempt $($attempts + 1) of $maxAttempts... $response.StatusCode "
            Start-Sleep -Seconds 10
            $attempts++
          }

          if ($attempts -ge $maxAttempts) {
            throw "Timed out waiting for Tomcat to start and serve requests."
          }
        }

    - name: Start ngrok and expose Tomcat port
      run: |
        # Start ngrok and expose Tomcat port
        Invoke-WebRequest 'https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip' -OutFile 'ngrok-stable-windows-amd64.zip'
        Expand-Archive -Path '.\ngrok-stable-windows-amd64.zip' -DestinationPath '.\'
        java -version
        .\ngrok authtoken 1x4H0neaMfnRX0ATJsuLhMP3lt3_tEj68PPQBGSMmY8wZMHH
        .\ngrok.exe http 8080

##  File:  Install-Apache.ps1
##  Desc:  Install Apache HTTP Server
################################################################################


       

        
       

       
       
